### ISSUE TITLE
InvalidArgumentException:Key "parameters.project.backendUrl"

### ISSUE THREAD

**Issue by kacurez** [keboola/gooddata-writer-v3#10]
Pustim load data ktory v parameters.project obsahuje iba `pid` ktory je provisionovany a spadne to na hlaske `InvalidArgumentException:Key "parameters.project.backendUrl"`

https://github.com/keboola/gooddata-writer-v3/blob/bef026605606d9d246cc28386adffd060641bf00/src/Component.php#L47-L58

v dokumentacii je `backendUrl` optional takze by to natom ife nemalo spadnut ale spadne.

**Comment by JakubMatejka** [comment]
Měla ta hláška nějakej stack trace? Zní dost divně, ale tipoval bych to na tohle: https://github.com/keboola/gooddata-writer-v3/pull/11/files

**Comment by kacurez** [comment]
jj to bude tym
