### ISSUE TITLE
Bad DATE handling

### ISSUE THREAD

**Issue by padak** [keboola/gooddata-writer-v3#23]
Mám tabulku v Shared Configu (https://connection.keboola.com/admin/projects/258/storage#/tables/out.c-new-billing.snowflake_cost), která starám writerem v pohodě do GD poslat jde (https://connection.keboola.com/admin/projects/258/jobs/478939554) a nový hodí chybu na blbě naformátovaném datumu:

![image](https://user-images.githubusercontent.com/1427901/51501775-92389f00-1dd3-11e9-8871-7786553bae14.png)

Nastavený je ten nový writer tady: https://connection.keboola.com/admin/projects/258/writers/keboola.gooddata-writer/478937920/table/out.c-new-billing.snowflake_cost

V tabulce rozhodně není nic než >=2018:

```
SELECT DISTINCT
  YEAR("DATE"::DATE),
  MONTH("DATE"::DATE)
  FROM "OUT"
  ORDER BY 1,2
```
![image](https://user-images.githubusercontent.com/1427901/51501805-b5fbe500-1dd3-11e9-98bb-5da25270c56e.png)

**Comment by JakubMatejka** [comment]
Zřejmě půjde o https://github.com/keboola/gooddata-writer-v3/pull/24
