### ISSUE TITLE
date dimension with custom identifier failed to load more times

### ISSUE THREAD

**Issue by kacurez** [keboola/gooddata-writer-v3#29]
naklikam si datumovu dimenziu s custom identifier takto .
![image](https://user-images.githubusercontent.com/1412120/52714749-f990db80-2f9a-11e9-9935-0fbaaaa82dd6.png)

```
"dimensions": {
        "testidntifier": {
          "identifier": "optionalIdentifier",
          "includeTime": false,
          "template": "gooddata"
        }
      },
```

Priradim nejakemu DATE stlpcu
![image](https://user-images.githubusercontent.com/1412120/52714881-4d9bc000-2f9b-11e9-9853-bb549fd54f12.png)

Prvy load(run writer config) prebehne bez problemov ale druhy bez akejkolvek zmeny v konfigu uz vzdy spadne na chybe

```
{
  "wTaskStatus": {
    "messages": [
      {
        "error": {
          "parameters": [
            "164",
            "optionalIdentifier.dim_date, optionalIdentifier.aac81lMifn6q, optionalIdentifier.aai81lMifn6q, optionalIdentifier.aao81lMifn6q, optionalIdentifier.aaE81lMifn6q, optionalIdentifier.aaK81lMifn6q, optionalIdentifier.aaQ81lMifn6q, optionalIdentifier.aa681lMifn6q"
          ],
          "requestId": "n5eq3hiipSBHBkSA:5CsOR09gGD2INzqE:h4d9iv8dv7zsisvn",
          "component": "Util::MDLoad",
          "errorClass": "GDC::Exception::User",
          "message": "Some objects (%s) already exist in metadata (%s)"
        }
      }
    ],
    "poll": "/gdc/md/rfqekh55mpyq37rbdznx1cvsctqum90d/tasks/4fec83b6802361fa77e8ad0c552422fa0000062e/status",
    "status": "ERROR",
    "links": {
      "poll": "/gdc/md/rfqekh55mpyq37rbdznx1cvsctqum90d/tasks/4fec83b6802361fa77e8ad0c552422fa0000062e/status"
    }
  }
}
```

Samozrejme ak dam load bez update modelu tak to preide ale ziadny iny update modelu som nerobil tak myslim ze by to nemalo spadnut

**Comment by kacurez** [comment]
@JakubMatejka tu si moc neviem rady, mohol by si sa nato prosim mrknut alebo ma aspon nejak nasmerovat?

**Comment by JakubMatejka** [comment]
Hm, pěkný. ;o) Poslal jsem ticket do GD jestli by nám nedokázali zjistit nějaký podrobnosti (na jakým API callu to přesně spadlo).

**Comment by JakubMatejka** [comment]
Tak hurá, pomohlo to (https://github.com/keboola/gooddata-writer-v3/pull/30)
