### ISSUE TITLE
custom templated dimensions not supported

### ISSUE THREAD

**Issue by kacurez** [keboola/gooddata-writer-v3#31]
Vytvorim si date dimension typu custom s nejakym templateId
![image](https://user-images.githubusercontent.com/1412120/53173222-87964300-35e7-11e9-88a4-6af8d838a12e.png)
ulozi sa to ako
![image](https://user-images.githubusercontent.com/1412120/53173329-be6c5900-35e7-11e9-8bca-e4407f5e7db9.png)
Po naslednom pusteni load spadne na chybe:
`Unrecognized option "templateId" under "root.parameters.dimensions.customdimension". Did you mean "template"?`

V starom gd writery to mozne bolo vytvorit si to cez nasledujuci dialog:

![image](https://user-images.githubusercontent.com/1412120/53173890-e01a1000-35e8-11e9-8d87-93284468f70a.png)

ktory sa potom do konfigu ulozil cca takto:

```
{
  "configuration": {
    "dimensions": {
      "DDD": {
        "identifier": "ddd.foo_cdd",
        "includeTime": false,
        "isExported": true,
        "template": "custom",
        "title": "DDD"
      },
```

ako by take nieco slo v novom writery?

**Comment by JakubMatejka** [comment]
Počkat, ale to popisuješ dvě různý věci. Ve starým Writeru se dala nastavit `template` datumové dimenze na default (`gooddata`), `keboola` nebo nějakou jinou (custom).

O co se ale snaží nový ui je, že chce vytvořit vlastně "custom" dimenzi z templaty `custom`. A ta (nejspíš) potřebuje v konfiguraci navíc ještě nějaký `templateId`? Pokud jo, tak novej Writer s ničím takovým zatím nepočítá a pokud se správně dívám, tak ve starým nic takovýho taky nešlo. (Sorry jestli jsme to už řešili, ale já si to už nepamatuju ;o) Zeptám se Matějkyse

**Comment by JakubMatejka** [comment]
Mně spíš přijde, že to nový ui ukládá blbě, že by mělo do `template` uložit obsah `templateId` (a žádný `template: custom` by tam být nemělo, ale pro jistotu to ještě ověřuju

**Comment by kacurez** [comment]
Stary writer uklada templateId pod template property takze to bude asi fakt chyba ui ako naznacujes.
Ja sa uz bohuzial nepamatam preco sme to urobili cez templateId, tak to skusim na ui prehodit a asi bude treba upravit aj migraciu.

**Comment by JakubMatejka** [comment]
Ok, migraci fixnu zítra.

**Comment by JakubMatejka** [comment]
mělo by být vyřešený
