### ISSUE TITLE
Invalid options - Loading data after migration

### ISSUE THREAD

**Issue by pivnicek** [keboola/gooddata-writer-v3#32]
Not sure if this belongs here or in UI or somewhere else:

After migrating, there are invalid options errors when trying to load data.

for example: 
```
Unrecognized options "tableId, ignoreFilter, incrementalLoad" under "root.parameters.tables.out.c-main.out_product_baskets". Available options are "columns", "disabled", "grain", "identifier", "title"
```

**Comment by pivnicek** [comment]
Sorry, there was another different invalid option

`Unrecognized option "templateId" under "root.parameters.dimensions.Fiscal". Did you mean "template"?`

**Comment by kacurez** [comment]
takto to vypada adekvatny konfig stareho writeru:
![image](https://user-images.githubusercontent.com/1412120/54199429-2f0ce400-44c9-11e9-87c3-74ac6ce482a3.png)
Ako sme sa bavili v https://github.com/keboola/gooddata-writer-v3/issues/31#issuecomment-466046264 to templateId by tam nemalo byt, to bude problem migracie ale tam ziadny templateId nevidim zeby sa pridaval. https://github.com/keboola/config-migration-tool/blob/master/src/Keboola/ConfigMigrationTool/Migration/KeboolaGoodDataWriterMigration.php

Aha tak v mastri to je ale nasadene to neni(https://github.com/keboola/config-migration-tool/releases), predtym to totiz templateId pridavalo a sme to davali prec no este to neni nasadene.

**Comment by pivnicek** [comment]
`customTemplate` is another invalid date dimension option
`Unrecognized option "customTemplate" under "root.parameters.dimensions.Date". Available options are "identifier", "includeTime", "template".`

**Comment by kacurez** [comment]
`customTemplate` in the config is caused by a UI bug, it temporarly saves customTemplate and remove it before saving:
https://github.com/keboola/kbc-ui/blob/7f0210ffe6c5e4ffbe7b6108520c428a60ee6438/src/scripts/modules/gooddata-writer/actionCreators.js#L598-L605
But if template option is during editing switched from custom to to e.g. gooddata dimension template then it isn't removed. 
So yes it should be ignored in the migration. I will create a migration tool fix PR .

**Comment by kacurez** [comment]
@pivnicek the fix^^ has been deployed, so please try the migration again.

**Comment by pivnicek** [comment]
@kacurez will this also solve the `templateId` issue?

**Comment by kacurez** [comment]
@pivnicek yes

**Comment by pivnicek** [comment]
dalsi: `Invalid type for path "root.parameters.tables.out.c-main.aa_visits.grain". Expected array, but got string`

**Comment by kacurez** [comment]
if grain is reset in the old config it is saved as an empty string, so it gets to the migrated config after migration. I will prepare fix in migration tool again.

**Comment by kacurez** [comment]
@pivnicek the fix^^ has just been deployed so can try to migrate it again.

**Comment by pivnicek** [comment]
Ok, I think that's all of the `invalid options` type
