### ISSUE TITLE
Orchestration after migration - route not found

### ISSUE THREAD

**Issue by pivnicek** [keboola/gooddata-writer-v3#34]
If you migrate, and leave it, then the orchestration tries to run the new migrated config, it fails with `route not found`  (Not sure if this is UI or migration tool or this repo)

**Comment by ondrejhlavacek** [comment]
(https://keboola.zendesk.com/agent/tickets/10010, https://keboola.zendesk.com/agent/tickets/10012)

**Comment by kacurez** [comment]
this one is fixed see https://github.com/keboola/config-migration-tool/pull/67
